### ISSUE TITLE
[3.3.2] Transition to self with history is confusing and/or borked

### ISSUE THREAD

**Issue by avaragado** [davidkpiano/xstate#133]
I'm unsure whether this is a code bug, a documentation bug,  a problem with my mental model, or a combination of all three in various doses.

See https://codesandbox.io/s/0487z2k1ln

```js
const { Machine } = require("xstate");

const machine = Machine({
    key: "test",
    initial: "first", // try with "second"
    states: {
        first: {
            on: {
                NEXT: "second",
            },
        },
        second: {
            initial: "nested",
            states: {
                nested: {},
                hist: {
                    history: true,
                },
            },
            on: {
                // doesn't work:
                // "TypeError: Cannot convert undefined or null to object"
                // NEXT: '.hist',

                // note the array
                NEXT: [
                    {
                        // doesn't work (reasonable error):
                        // target: 'hist',
                        //
                        // doesn't work:
                        // "TypeError: Cannot convert undefined or null to object"
                        target: ".hist",
                        //
                        // doesn't work:
                        // "TypeError: Cannot convert undefined or null to object"
                        // target: 'second.hist',
                        // internal: true,
                        //
                        // works:
                        // target: 'second',
                        // internal: true,
                    },
                ],
            },
        },
    },
});

const log = (ix, state) => {
    console.log(`${ix}\n\n${JSON.stringify(state, null, 4)}\n\n`);
};

log(1, machine.initialState);

const state2 = machine.transition(machine.initialState, "NEXT");

log(2, state2);

const state3 = machine.transition(state2, "NEXT");

log(3, state3);
```

Output:

```

1

{
    "value": "first",
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
}

 
2

{
    "value": {
        "second": "nested"
    },
    "history": {
        "value": "first",
        "actions": [],
        "activities": {},
        "data": {},
        "events": []
    },
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
}

 
Error in sandbox: 
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.toStatePaths (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/utils.js:103:41)
    at StateNode.resolveHistory (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:723:44)
    at StateNode.getFromRelativePath (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:698:35)
    at StateNode.getFromRelativePath (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:703:31)
    at StateNode.getRelativeStateNodes (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:652:50)
    at eval (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:285:26)
    at Array.map (<anonymous>)
    at StateNode._next (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:284:63)
    at StateNode._transitionLeafNode (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:107:27)
    at StateNode._transition (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:229:25)
    at StateNode._transitionHierarchicalNode (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:127:30)
    at StateNode._transition (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:233:25)
    at StateNode.transition (https://0487z2k1ln.codesandbox.io/node_modules/xstate/lib/StateNode.js:413:36)
    at evaluate (https://0487z2k1ln.codesandbox.io/src/index.js:61:22)
    at ie (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:519511)
    at e.value (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:531419)
    at e.value (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:503018)
    at d (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:531213)
    at loadResources (https://0487z2k1ln.codesandbox.io/index.html:11:2)
    at evaluate (https://0487z2k1ln.codesandbox.io/index.html:17:3)
    at ie (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:519511)
    at e.value (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:531419)
    at https://codesandbox.io/static/js/sandbox.1bf96048.js:259:502689
    at Array.forEach (<anonymous>)
    at e.value (https://codesandbox.io/static/js/sandbox.1bf96048.js:259:502660)
    at https://codesandbox.io/static/js/sandbox.1bf96048.js:259:322616
    at g (https://codesandbox.io/static/js/common-sandbox.6968697b.js:13:14177)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.6968697b.js:13:13965)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.6968697b.js:13:14356)
    at n (https://codesandbox.io/static/js/common-sandbox.6968697b.js:13:51303)
    at https://codesandbox.io/static/js/common-sandbox.6968697b.js:13:51399
```

From the [Internal transitions doc](http://davidkpiano.github.io/xstate/docs/#/guides/internal), I expected both `target: ".hist"` and `target "second.hist"/internal: true` to work. As far as I can see the shape of the machine is identical to the left/right/center/justify example in that doc, but using a history state.

And yet the `target "second"/internal: true` combo works. (The `internal` is there because in the code I've derived this from, I'm emitting actions that I don't want to re-emit on this transition.)

What's also interesting is if you change the machine's initial state from "first" to "second". In this case I expected the machine to blow up sooner, on the first `NEXT` event, since all this change effectively does is skip a required `NEXT` to get to `second`. But here's what happens:

```

1

{
    "value": {
        "second": "nested"
    },
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
}

 
2

{
    "value": {
        "second": "nested"
    },
    "history": {
        "value": {
            "second": "nested"
        },
        "actions": [],
        "activities": {},
        "data": {},
        "events": []
    },
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
}

 
3

{
    "value": {
        "second": "nested"
    },
    "history": {
        "value": {
            "second": "nested"
        },
        "actions": [],
        "activities": {},
        "data": {},
        "events": []
    },
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
}
```

**Comment by dannsam** [comment]
I also getting issues with nested history, got a failing test case that I'd expected to pass. It feels that history should be nested for composite machines. I might have a look at working on a PR.

```js
describe('multistage history states', () => {
  const pcWithTurboButtonMachine = Machine({
    key: 'pc-with-turbo-button',
    initial: 'off',
    states: {
      off: {
        on: { POWER: 'starting' }
      },
      starting: {
        on: { STARTED: 'running.H' }
      },
      running: {
        initial: 'normal',
        states: {
          normal: {
            on: { SWITCH_TURBO: 'turbo' }
          },
          turbo: {
            on: { SWITCH_TURBO: 'normal' }
          },
          H: {
            history: true
          }
        },
        on: {
          POWER: 'off'
        }
      }
    }
  });

  it('should go to the most recently visited state', () => {
    const onTurboState = pcWithTurboButtonMachine.transition('running', 'SWITCH_TURBO');
    const offState = pcWithTurboButtonMachine.transition(onTurboState, 'POWER');
    const loadingState = pcWithTurboButtonMachine.transition(offState, 'POWER');

    assert.equal(
      pcWithTurboButtonMachine.transition(loadingState, 'STARTED').toString(),
      'running.turbo'
    );
  });
});
```

Currently, the test fails with error 
```
     TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at Object.exports.toStatePaths (src\utils.ts:134:12)
      at StateNode.resolveHistory (src\StateNode.ts:1117:9)
      at StateNode.getFromRelativePath (src\StateNode.ts:1085:29)
      at StateNode.getFromRelativePath (src\StateNode.ts:1092:27)
      at StateNode.getRelativeStateNodes (src\StateNode.ts:1019:48)
      at src\StateNode.ts:500:14
      at Array.map (<anonymous>)
      at StateNode._next (src\StateNode.ts:499:24)
      at StateNode._transitionLeafNode (src\StateNode.ts:187:28)
      at StateNode._transition (src\StateNode.ts:410:19)
      at StateNode.transition (src\StateNode.ts:702:34)
      at Context.<anonymous> (test\history.test.ts:198:32)
```

**Comment by davidkpiano** [comment]
Can any of you create a PR with a failing test case? You can copy-paste these examples in `history.test.ts`. Would help a lot!
