### ISSUE TITLE
Is initial state is mandatory for compound state machines?

### ISSUE THREAD

**Issue by karikalanarun** [davidkpiano/xstate#584]
## Bug or feature request?
Bug

## Description:
I used a compound type state in a state machine. see below, 
```
const RemoveMachine = Machine(Machine({
    initial: 'hide',
    states: {
        hide: {
            on: {
                SHOW: 'show',
            },
        },
        show: {
            states: {
                remove: {},
                cancel: {},
                error: { meta: { message: 'Something Went Wrong' } },
                finish: { type: 'final' },
            },
        },
    },
});)
```

And when I'm trying to test the transition 'hide' -> 'show' on 'SHOW' event.

```
RemoveUserMachine.transition(
            'hide',
           'SHOW'
        )
```

## (Bug) Expected result:
I expect the next state.

## (Bug) Actual result:
But, the some unwanted and not understandable error thrown like below,

> at StateTree.get [as done] (node_modules/xstate/src/StateTree.ts:71:26)
      at StateTree.Object.<anonymous>.StateTree.getDoneEvents (node_modules/xstate/src/StateTree.ts:140:15)
      at node_modules/xstate/src/StateTree.ts:124:32
          at Array.map (<anonymous>)
      at StateTree.Object.<anonymous>.StateTree.getDoneEvents (node_modules/xstate/src/StateTree.ts:123:24)
      at StateNode.Object.<anonymous>.StateNode.getActions (node_modules/xstate/src/StateNode.ts:1035:25)
      at StateNode.Object.<anonymous>.StateNode.resolveTransition (node_modules/xstate/src/StateNode.ts:1175:26)
      at StateNode.Object.<anonymous>.StateNode.transition (node_modules/xstate/src/StateNode.ts:1141:17)
      at Object.transition (src/app/ManageUsers/__tests__/machine.removeUser.ts:11:40)

**Comment by davidkpiano** [comment]
You don't have an `initial` state on `show`. Add one, and the error will go away.
