### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by dodo** [davidkpiano/xstate#79]
```
> Machine=require('xstate').Machine
[Function: Machine]
> Machine({parallel:true}).initialState
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at StateNode.getStateNodes (…/xstate/lib/index.js:70:14)
    at StateNode.get [as initialState] (…/xstate/lib/index.js:274:37)
```

https://github.com/davidkpiano/xstate/blob/ad485c3c8d9da46a93cb9e3aba78dd2f53744d8b/src/StateNode.ts#L119
changing that to `.reduce((a, b) => a.concat(b), [])` seems to do the trick:
```
> Machine({parallel:true}).initialState
State { value: {}, history: undefined, actions: [] }
```

**Comment by davidkpiano** [comment]
Makes sense, want to make a quick PR?
