### ISSUE TITLE
import fails - environment.js file missing from 4.7.0-rc7? 

### ISSUE THREAD

**Issue by rjrodger** [davidkpiano/xstate#829]
**Description**
Importing xstate fails with:

`
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './environment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/richard/Projects/seneca/msg-run/node_modules/xstate/lib/utils.js:46:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
`

Reverted to version 4.6.7 and this error does not occur - module loads as expected.

**Expected Result**
`import` statement succeeds.

**Actual Result**
`import` throws exception as above.

**Reproduction**
`import { Machine } from 'xstate'` // that's it

**Additional context**
Occurs with 4.7.0-rc7

**Comment by rjrodger** [comment]
$ node -v
v10.15.3

**Comment by davidkpiano** [comment]
Sorry about that! Should work now, and `xstate` is now on `4.7` (release notes coming soon)
